# Generated by Django 5.0.2 on 2024-04-12 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('competitionName', models.CharField(max_length=50)),
                ('dateToStart', models.DateField()),
                ('dateToEnd', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('CompetitionPrivacy', models.CharField(max_length=20)),
                ('registration_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('numberPhone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=24)),
                ('position', models.CharField(max_length=25)),
                ('dataOfRegistration', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatesId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('numberPhone', models.CharField(max_length=15)),
                ('academic_level', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('country', models.CharField(default='Cameroon', max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('city_of_origin', models.CharField(default='Douala', max_length=100)),
                ('dataOfRegistration', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('registration_fee_status', models.CharField(max_length=20)),
                ('id_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starbeautyvote.competition')),
            ],
        ),
    ]
