# Generated by Django 5.0.2 on 2024-04-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starbeautyvote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='id_promote',
            new_name='id_promoter',
        ),
        migrations.RenameField(
            model_name='promoter',
            old_name='userId',
            new_name='promoterId',
        ),
    ]
