# Generated by Django 5.0.2 on 2024-04-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starbeautyvote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dataOfRegistration',
            new_name='dataJoined',
        ),
    ]
