# Generated by Django 5.0.2 on 2024-04-06 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbeautyvote', '0002_rename_dataofregistration_user_datajoined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('competitionName', models.CharField(max_length=50)),
                ('dateToStart', models.DateField()),
                ('dateToEnd', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('CompetitionPrivacy', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dataJoined',
            new_name='dataOfRegistration',
        ),
    ]
