# Generated by Django 5.0.2 on 2024-04-08 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbeautyvote', '0003_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatesId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fullName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('numberPhone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('taille', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Photographies', models.ImageField(upload_to='')),
                ('etude', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dataOfRegistration', models.DateField(auto_now=True)),
            ],
        ),
    ]
